[versions]
agp = "8.6.1"
kotlin = "2.0.0"
coreKtx = "1.15.0"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
lifecycleRuntimeKtx = "2.8.7"
activityCompose = "1.10.1"
composeBom = "2025.04.01"
compose-coil = "2.4.0"
lottieCompose = "6.4.0"
retrofit = "2.9.0"
okhttp3 = "4.10.0"
retrofit2KotlinxSerializationConverter = "0.8.0"
timber_version = "5.0.1"
hilt = "2.51.1"
hiltExt = "1.2.0"
extended-icon = "1.6.8"
composeNavigation = "2.8.9"
serialization = "1.6.3"
androidx-core-splashscreen = "1.0.1"
androidx-lifecycle = "2.8.3"
androidx-paging = "3.3.1"
room-version = "2.7.1"
constraintlayout = "2.1.4"
ksp = "2.0.0-1.0.21"
androidxHiltNavigationCompose = "1.2.0"
animation = "1.8.0"
constraintlayoutCompose = "1.1.1"
datastorePreferences = "1.1.1"
andoroidMedia3 = "1.3.0"




[libraries]
androidx-animation = { module = "androidx.compose.animation:animation", version.ref = "animation" }
androidx-constraintlayout-compose = { module = "androidx.constraintlayout:constraintlayout-compose", version.ref = "constraintlayoutCompose" }
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastorePreferences" }
androidx-datastore-preferences-core = { module = "androidx.datastore:datastore-preferences-core", version.ref = "datastorePreferences" }
androidx-core-splashscreen = { group = "androidx.core", name = "core-splashscreen", version.ref = "androidx-core-splashscreen" }

androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-material = { group = "androidx.compose.material", name = "material" }

hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "hilt" }
androidx-hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "androidxHiltNavigationCompose" }
hilt-ext-compiler = { module = "androidx.hilt:hilt-compiler", version.ref = "hiltExt" }

lottie-compose = { module = "com.airbnb.android:lottie-compose", version.ref = "lottieCompose" }
retrofit2-kotlinx-serialization-converter = { module = "com.jakewharton.retrofit:retrofit2-kotlinx-serialization-converter", version.ref = "retrofit2KotlinxSerializationConverter" }
timber = { group = "com.jakewharton.timber", name = "timber", version.ref = "timber_version" }

retrofit-converter-scalars = { group = "com.squareup.retrofit2", name = "converter-scalars", version.ref = "retrofit" }
retrofit-converter-gson = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "retrofit" }
okhttp3-logging-interceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttp3" }

navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "composeNavigation" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization" }
material-icon = { group = "androidx.compose.material", name = "material-icons-extended", version.ref = "extended-icon" }

compose-coil = { group = "io.coil-kt", name = "coil-compose", version.ref = "compose-coil" }
compose-coil-svg = { group = "io.coil-kt", name = "coil-svg", version.ref = "compose-coil" }
compose-room-compiler = {group = "androidx.room", name = "room-compiler", version.ref = "room-version" }
compose-room-paging = {group = "androidx.room", name = "room-paging", version.ref = "room-version" }
compose-room-runtime = {group = "androidx.room", name = "room-runtime", version.ref = "room-version" }
compose-room-ktx = {group = "androidx.room", name = "room-ktx", version.ref = "room-version" }

android-media3-player = {group="androidx.media3", name= "media3-exoplayer", version.ref = "andoroidMedia3"}
android-media3-player-ui = {group="androidx.media3", name= "media3-ui", version.ref = "andoroidMedia3"}

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
room-compiler = { id = "androidx.room", version.ref = "room-version" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
hiltAndroid = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
kotlinAndroidKsp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
